#!/bin/bash
here_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
program_dir=$1
program_name=$(basename "${program_dir}")
program_dir="${program_dir}/base"
program_df="${program_dir}/.Dockerfile"
source_file=$(cd "${program_dir}/source" && find . -name "*.c")
source_file=$(echo "${source_file}" | sed "s#./##")
gcc_libs=$(cat "${program_dir}/gcc-libs.txt")

echo "Building siemens program: ${program_name}"

cp "${here_dir}/Dockerfile.program" "${program_df}"
sed -i "s#<<PROGRAM_NAME>>#${program_name}#" "${program_df}"
sed -i "s#<<EXECUTABLE>>#${program_name}#" "${program_df}"
sed -i "s#<<SOURCE_FILE>>#${source_file}#" "${program_df}"
sed -i "s#<<GCC_LIBS>>#${gcc_libs}#" "${program_df}"

docker build \
  -f "${program_dir}/.Dockerfile" \
  -t christimperley/repairbox:siemens-${program_name}-base \
  "${program_dir}" > /dev/null
