#!/usr/bin/python3
import os
import json

def build_manifest():
    tests = []
    with open("tests.txt", "r") as f:
        for command in f:
            (args, _, inpt) = command.rpartition('< ')
            (args, inpt) = (args.strip(), inpt.strip())
            command = "<<EXECUTABLE>> {} < <<SANDBOX>>/{}".format(args, inpt)
            test = {
                'command': command,
                'input': {inpt: inpt}
            }
            tests.append(test)

    # write to file
    with open("tests.pythia.json", "w") as f:
        json.dump(tests, f, indent=2, sort_keys=True)

    # destroy list of tests
    os.remove("tests.txt")
    

if __name__ == "__main__":
    build_manifest()
