# This is the base Dockerfile used by all of the PHP ManyBugs scenarios; it
# provides a minimal environment required to build PHP from source on a
# 64-bit Fedora machine
FROM repairbox:slim64
MAINTAINER Chris Timperley "christimperley@gmail.com"
