#!/bin/sh
#
# STImpL Test Script generated by 
# MakeTestScript on Nov 8, 2016 at 2:18:19 PM
# by the command: 
#  java sir.mts.MakeTestScript "--no-escapes" "--stimple-file" "../testplans.alt
#  /v0/v0.cov.universe.esc" "--script-name" "test.sh" "--experiment-dir" ".." "-
#  -exe-name" "../source/grep.exe" "--compare-outputs" "../outputs.alt" "cmp -s"
#   "--target" "bsh" "--print-config"

echo ">>>>>>>>running test 1"
../source/grep.exe -0 12345 ../inputs/grep1.dat  > ../outputs/t1 2>&1
cmp -s ../outputs/t1 ../outputs.alt/t1 || echo different results

echo ">>>>>>>>running test 2"
../source/grep.exe -1 12345 ../inputs/grep1.dat  > ../outputs/t2 2>&1
cmp -s ../outputs/t2 ../outputs.alt/t2 || echo different results

echo ">>>>>>>>running test 3"
../source/grep.exe -2 12345 ../inputs/grep1.dat  > ../outputs/t3 2>&1
cmp -s ../outputs/t3 ../outputs.alt/t3 || echo different results

echo ">>>>>>>>running test 4"
../source/grep.exe -3 12345 ../inputs/grep1.dat  > ../outputs/t4 2>&1
cmp -s ../outputs/t4 ../outputs.alt/t4 || echo different results

echo ">>>>>>>>running test 5"
../source/grep.exe -4 12345 ../inputs/grep1.dat  > ../outputs/t5 2>&1
cmp -s ../outputs/t5 ../outputs.alt/t5 || echo different results

echo ">>>>>>>>running test 6"
../source/grep.exe -5 12345 ../inputs/grep1.dat  > ../outputs/t6 2>&1
cmp -s ../outputs/t6 ../outputs.alt/t6 || echo different results

echo ">>>>>>>>running test 7"
../source/grep.exe -6 12345 ../inputs/grep1.dat  > ../outputs/t7 2>&1
cmp -s ../outputs/t7 ../outputs.alt/t7 || echo different results

echo ">>>>>>>>running test 8"
../source/grep.exe -7 12345 ../inputs/grep1.dat  > ../outputs/t8 2>&1
cmp -s ../outputs/t8 ../outputs.alt/t8 || echo different results

echo ">>>>>>>>running test 9"
../source/grep.exe -8 12345 ../inputs/grep1.dat  > ../outputs/t9 2>&1
cmp -s ../outputs/t9 ../outputs.alt/t9 || echo different results

echo ">>>>>>>>running test 10"
../source/grep.exe -9 12345 ../inputs/grep1.dat  > ../outputs/t10 2>&1
cmp -s ../outputs/t10 ../outputs.alt/t10 || echo different results

echo ">>>>>>>>running test 11"
../source/grep.exe -f 12345 ../inputs/grep1.dat  > ../outputs/t11 2>&1
cmp -s ../outputs/t11 ../outputs.alt/t11 || echo different results

echo ">>>>>>>>running test 12"
../source/grep.exe -i 12345 ../inputs/grep1.dat  > ../outputs/t12 2>&1
cmp -s ../outputs/t12 ../outputs.alt/t12 || echo different results

echo ">>>>>>>>running test 13"
../source/grep.exe -Y 12345 ../inputs/grep1.dat  > ../outputs/t13 2>&1
cmp -s ../outputs/t13 ../outputs.alt/t13 || echo different results

echo ">>>>>>>>running test 14"
../source/grep.exe -A -12345 ../inputs/grep1.dat  > ../outputs/t14 2>&1
cmp -s ../outputs/t14 ../outputs.alt/t14 || echo different results

echo ">>>>>>>>running test 15"
../source/grep.exe -B -12345 ../inputs/grep1.dat  > ../outputs/t15 2>&1
cmp -s ../outputs/t15 ../outputs.alt/t15 || echo different results

echo ">>>>>>>>running test 16"
../source/grep.exe -F -E 12345 ../inputs/grep1.dat  > ../outputs/t16 2>&1
cmp -s ../outputs/t16 ../outputs.alt/t16 || echo different results

echo ">>>>>>>>running test 17"
../source/grep.exe -E -F 12345 ../inputs/grep1.dat  > ../outputs/t17 2>&1
cmp -s ../outputs/t17 ../outputs.alt/t17 || echo different results

echo ">>>>>>>>running test 18"
../source/grep.exe -E -G 12345 ../inputs/grep1.dat  > ../outputs/t18 2>&1
cmp -s ../outputs/t18 ../outputs.alt/t18 || echo different results

echo ">>>>>>>>running test 19"
../source/grep.exe -G -X 12345 ../inputs/grep1.dat  > ../outputs/t19 2>&1
cmp -s ../outputs/t19 ../outputs.alt/t19 || echo different results

echo ">>>>>>>>running test 20"
../source/grep.exe -f nosuchfile ../inputs/grep1.dat  > ../outputs/t20 2>&1
cmp -s ../outputs/t20 ../outputs.alt/t20 || echo different results

echo ">>>>>>>>running test 21"
../source/grep.exe -f ../inputs/grep1.dat ../inputs/grep1.dat  > ../outputs/t21 2>&1
cmp -s ../outputs/t21 ../outputs.alt/t21 || echo different results

echo ">>>>>>>>running test 22"
../source/grep.exe -c 12345a < ../inputs/grep1.dat > ../outputs/t22 2>&1
cmp -s ../outputs/t22 ../outputs.alt/t22 || echo different results

echo ">>>>>>>>running test 23"
../source/grep.exe 12345a < ../inputs/grep1.dat > ../outputs/t23 2>&1
cmp -s ../outputs/t23 ../outputs.alt/t23 || echo different results

echo ">>>>>>>>running test 24"
../source/grep.exe -c include < ../inputs/grep1.dat > ../outputs/t24 2>&1
cmp -s ../outputs/t24 ../outputs.alt/t24 || echo different results

echo ">>>>>>>>running test 25"
../source/grep.exe include < ../inputs/grep1.dat > ../outputs/t25 2>&1
cmp -s ../outputs/t25 ../outputs.alt/t25 || echo different results

echo ">>>>>>>>running test 26"
../source/grep.exe include ../inputs/grep1.dat  > ../outputs/t26 2>&1
cmp -s ../outputs/t26 ../outputs.alt/t26 || echo different results

echo ">>>>>>>>running test 27"
../source/grep.exe -l include < ../inputs/../inputs/grep1.dat > ../outputs/t27 2>&1
cmp -s ../outputs/t27 ../outputs.alt/t27 || echo different results

echo ">>>>>>>>running test 28"
../source/grep.exe -L 12345a < ../inputs/../inputs/grep1.dat > ../outputs/t28 2>&1
cmp -s ../outputs/t28 ../outputs.alt/t28 || echo different results

echo ">>>>>>>>running test 29"
../source/grep.exe 12345a < ../inputs/../inputs/grep1.dat > ../outputs/t29 2>&1
cmp -s ../outputs/t29 ../outputs.alt/t29 || echo different results

echo ">>>>>>>>running test 30"
../source/grep.exe "--" 12345 ../inputs/grep1.dat  > ../outputs/t30 2>&1
cmp -s ../outputs/t30 ../outputs.alt/t30 || echo different results

echo ">>>>>>>>running test 31"
../source/grep.exe - -- 12345 ../inputs/grep1.dat  > ../outputs/t31 2>&1
cmp -s ../outputs/t31 ../outputs.alt/t31 || echo different results

echo ">>>>>>>>running test 32"
../source/grep.exe "\[z-a]" ../inputs/grep1.dat  > ../outputs/t32 2>&1
cmp -s ../outputs/t32 ../outputs.alt/t32 || echo different results

echo ">>>>>>>>running test 33"
../source/grep.exe "\[5-1]" ../inputs/grep1.dat  > ../outputs/t33 2>&1
cmp -s ../outputs/t33 ../outputs.alt/t33 || echo different results

echo ">>>>>>>>running test 34"
../source/grep.exe "\[F-A]" ../inputs/grep1.dat  > ../outputs/t34 2>&1
cmp -s ../outputs/t34 ../outputs.alt/t34 || echo different results

echo ">>>>>>>>running test 35"
../source/grep.exe -ff  > ../outputs/t35 2>&1
cmp -s ../outputs/t35 ../outputs.alt/t35 || echo different results

echo ">>>>>>>>running test 36"
../source/grep.exe -f  > ../outputs/t36 2>&1
cmp -s ../outputs/t36 ../outputs.alt/t36 || echo different results

echo ">>>>>>>>running test 37"
../source/grep.exe 'a$a' ../inputs/grep1.dat  > ../outputs/t37 2>&1
cmp -s ../outputs/t37 ../outputs.alt/t37 || echo different results

echo ">>>>>>>>running test 38"
../source/grep.exe 'if$' ../inputs/grep1.dat  > ../outputs/t38 2>&1
cmp -s ../outputs/t38 ../outputs.alt/t38 || echo different results

echo ">>>>>>>>running test 39"
../source/grep.exe 'switch$|else' ../inputs/grep1.dat  > ../outputs/t39 2>&1
cmp -s ../outputs/t39 ../outputs.alt/t39 || echo different results

echo ">>>>>>>>running test 40"
../source/grep.exe "1\\+\\+" ../inputs/grep1.dat  > ../outputs/t40 2>&1
cmp -s ../outputs/t40 ../outputs.alt/t40 || echo different results

echo ">>>>>>>>running test 41"
../source/grep.exe "1\\?\\+" ../inputs/grep1.dat  > ../outputs/t41 2>&1
cmp -s ../outputs/t41 ../outputs.alt/t41 || echo different results

echo ">>>>>>>>running test 42"
../source/grep.exe "1\\+\\?" ../inputs/grep1.dat  > ../outputs/t42 2>&1
cmp -s ../outputs/t42 ../outputs.alt/t42 || echo different results

echo ">>>>>>>>running test 43"
../source/grep.exe "\[" ../inputs/grep1.dat  > ../outputs/t43 2>&1
cmp -s ../outputs/t43 ../outputs.alt/t43 || echo different results

echo ">>>>>>>>running test 44"
../source/grep.exe "a\[" ../inputs/grep1.dat  > ../outputs/t44 2>&1
cmp -s ../outputs/t44 ../outputs.alt/t44 || echo different results

echo ">>>>>>>>running test 45"
../source/grep.exe "a*\[" ../inputs/grep1.dat  > ../outputs/t45 2>&1
cmp -s ../outputs/t45 ../outputs.alt/t45 || echo different results

echo ">>>>>>>>running test 46"
../source/grep.exe "\[a" ../inputs/grep1.dat  > ../outputs/t46 2>&1
cmp -s ../outputs/t46 ../outputs.alt/t46 || echo different results

echo ">>>>>>>>running test 47"
../source/grep.exe "\[1" ../inputs/grep1.dat  > ../outputs/t47 2>&1
cmp -s ../outputs/t47 ../outputs.alt/t47 || echo different results

echo ">>>>>>>>running test 48"
../source/grep.exe "\[1-9" ../inputs/grep1.dat  > ../outputs/t48 2>&1
cmp -s ../outputs/t48 ../outputs.alt/t48 || echo different results

echo ">>>>>>>>running test 49"
../source/grep.exe "\[1-]" ../inputs/grep1.dat  > ../outputs/t49 2>&1
cmp -s ../outputs/t49 ../outputs.alt/t49 || echo different results

echo ">>>>>>>>running test 50"
../source/grep.exe "\[a-]" ../inputs/grep1.dat  > ../outputs/t50 2>&1
cmp -s ../outputs/t50 ../outputs.alt/t50 || echo different results

echo ">>>>>>>>running test 51"
../source/grep.exe "\[1a-]" ../inputs/grep1.dat  > ../outputs/t51 2>&1
cmp -s ../outputs/t51 ../outputs.alt/t51 || echo different results

echo ">>>>>>>>running test 52"
../source/grep.exe "\[\[:alpha:]-5]" ../inputs/grep1.dat  > ../outputs/t52 2>&1
cmp -s ../outputs/t52 ../outputs.alt/t52 || echo different results

echo ">>>>>>>>running test 53"
../source/grep.exe "\[z\[:digit:]-f]" ../inputs/grep1.dat  > ../outputs/t53 2>&1
cmp -s ../outputs/t53 ../outputs.alt/t53 || echo different results

echo ">>>>>>>>running test 54"
../source/grep.exe "\[\[:alnum:]-9]" ../inputs/grep1.dat  > ../outputs/t54 2>&1
cmp -s ../outputs/t54 ../outputs.alt/t54 || echo different results

echo ">>>>>>>>running test 55"
../source/grep.exe "\[1-2-9]" ../inputs/grep1.dat  > ../outputs/t55 2>&1
cmp -s ../outputs/t55 ../outputs.alt/t55 || echo different results

echo ">>>>>>>>running test 56"
../source/grep.exe "\[a-c-z]" ../inputs/grep1.dat  > ../outputs/t56 2>&1
cmp -s ../outputs/t56 ../outputs.alt/t56 || echo different results

echo ">>>>>>>>running test 57"
../source/grep.exe "\[1A-Z-A]" ../inputs/grep1.dat  > ../outputs/t57 2>&1
cmp -s ../outputs/t57 ../outputs.alt/t57 || echo different results

echo ">>>>>>>>running test 58"
../source/grep.exe "\[\[:digit:]-1-9]" ../inputs/grep1.dat  > ../outputs/t58 2>&1
cmp -s ../outputs/t58 ../outputs.alt/t58 || echo different results

echo ">>>>>>>>running test 59"
../source/grep.exe "\[\[:digit:]-A-Z]" ../inputs/grep1.dat  > ../outputs/t59 2>&1
cmp -s ../outputs/t59 ../outputs.alt/t59 || echo different results

echo ">>>>>>>>running test 60"
../source/grep.exe "\[\[:digit:]-a-z]" ../inputs/grep1.dat  > ../outputs/t60 2>&1
cmp -s ../outputs/t60 ../outputs.alt/t60 || echo different results

echo ">>>>>>>>running test 61"
../source/grep.exe "\[1-2-" ../inputs/grep1.dat  > ../outputs/t61 2>&1
cmp -s ../outputs/t61 ../outputs.alt/t61 || echo different results

echo ">>>>>>>>running test 62"
../source/grep.exe "\[1A-Z-" ../inputs/grep1.dat  > ../outputs/t62 2>&1
cmp -s ../outputs/t62 ../outputs.alt/t62 || echo different results

echo ">>>>>>>>running test 63"
../source/grep.exe "\[Aa-z-" ../inputs/grep1.dat  > ../outputs/t63 2>&1
cmp -s ../outputs/t63 ../outputs.alt/t63 || echo different results

echo ">>>>>>>>running test 64"
../source/grep.exe "\[1-" ../inputs/grep1.dat  > ../outputs/t64 2>&1
cmp -s ../outputs/t64 ../outputs.alt/t64 || echo different results

echo ">>>>>>>>running test 65"
../source/grep.exe "\[1A-" ../inputs/grep1.dat  > ../outputs/t65 2>&1
cmp -s ../outputs/t65 ../outputs.alt/t65 || echo different results

echo ">>>>>>>>running test 66"
../source/grep.exe "\[Aa-" ../inputs/grep1.dat  > ../outputs/t66 2>&1
cmp -s ../outputs/t66 ../outputs.alt/t66 || echo different results

echo ">>>>>>>>running test 67"
../source/grep.exe "\[\[:" ../inputs/grep1.dat  > ../outputs/t67 2>&1
cmp -s ../outputs/t67 ../outputs.alt/t67 || echo different results

echo ">>>>>>>>running test 68"
../source/grep.exe "a\[\[:" ../inputs/grep1.dat  > ../outputs/t68 2>&1
cmp -s ../outputs/t68 ../outputs.alt/t68 || echo different results

echo ">>>>>>>>running test 69"
../source/grep.exe "1-9\[\[:" ../inputs/grep1.dat  > ../outputs/t69 2>&1
cmp -s ../outputs/t69 ../outputs.alt/t69 || echo different results

echo ">>>>>>>>running test 70"
../source/grep.exe "\[\[:a:]]" ../inputs/grep1.dat  > ../outputs/t70 2>&1
cmp -s ../outputs/t70 ../outputs.alt/t70 || echo different results

echo ">>>>>>>>running test 71"
../source/grep.exe "\[\[:1:]]" ../inputs/grep1.dat  > ../outputs/t71 2>&1
cmp -s ../outputs/t71 ../outputs.alt/t71 || echo different results

echo ">>>>>>>>running test 72"
../source/grep.exe "\[\[:abcdefg:]]" ../inputs/grep1.dat  > ../outputs/t72 2>&1
cmp -s ../outputs/t72 ../outputs.alt/t72 || echo different results

echo ">>>>>>>>running test 73"
../source/grep.exe "\[\[:alpha:]" ../inputs/grep1.dat  > ../outputs/t73 2>&1
cmp -s ../outputs/t73 ../outputs.alt/t73 || echo different results

echo ">>>>>>>>running test 74"
../source/grep.exe "\[a\[:digit:]" ../inputs/grep1.dat  > ../outputs/t74 2>&1
cmp -s ../outputs/t74 ../outputs.alt/t74 || echo different results

echo ">>>>>>>>running test 75"
../source/grep.exe "\[\[:alnum:]" ../inputs/grep1.dat  > ../outputs/t75 2>&1
cmp -s ../outputs/t75 ../outputs.alt/t75 || echo different results

echo ">>>>>>>>running test 76"
../source/grep.exe "\\\{QUOTE} ../inputs/grep1.dat  > ../outputs/t76 2>&1
cmp -s ../outputs/t76 ../outputs.alt/t76 || echo different results

echo ">>>>>>>>running test 77"
../source/grep.exe "if\\" ../inputs/grep1.dat  > ../outputs/t77 2>&1
cmp -s ../outputs/t77 ../outputs.alt/t77 || echo different results

echo ">>>>>>>>running test 78"
../source/grep.exe "else\\" ../inputs/grep1.dat  > ../outputs/t78 2>&1
cmp -s ../outputs/t78 ../outputs.alt/t78 || echo different results

echo ">>>>>>>>running test 79"
../source/grep.exe '\\`' ../inputs/grep1.dat  > ../outputs/t79 2>&1
cmp -s ../outputs/t79 ../outputs.alt/t79 || echo different results

echo ">>>>>>>>running test 80"
../source/grep.exe 'if\\`' ../inputs/grep1.dat  > ../outputs/t80 2>&1
cmp -s ../outputs/t80 ../outputs.alt/t80 || echo different results

echo ">>>>>>>>running test 81"
../source/grep.exe '\\`else' ../inputs/grep1.dat  > ../outputs/t81 2>&1
cmp -s ../outputs/t81 ../outputs.alt/t81 || echo different results

echo ">>>>>>>>running test 82"
../source/grep.exe "\\'" ../inputs/grep1.dat  > ../outputs/t82 2>&1
cmp -s ../outputs/t82 ../outputs.alt/t82 || echo different results

echo ">>>>>>>>running test 83"
../source/grep.exe "if\\'" ../inputs/grep1.dat  > ../outputs/t83 2>&1
cmp -s ../outputs/t83 ../outputs.alt/t83 || echo different results

echo ">>>>>>>>running test 84"
../source/grep.exe "\\'else" ../inputs/grep1.dat  > ../outputs/t84 2>&1
cmp -s ../outputs/t84 ../outputs.alt/t84 || echo different results

echo ">>>>>>>>running test 85"
../source/grep.exe "\\1" ../inputs/grep1.dat  > ../outputs/t85 2>&1
cmp -s ../outputs/t85 ../outputs.alt/t85 || echo different results

echo ">>>>>>>>running test 86"
../source/grep.exe "\\2" ../inputs/grep1.dat  > ../outputs/t86 2>&1
cmp -s ../outputs/t86 ../outputs.alt/t86 || echo different results

echo ">>>>>>>>running test 87"
../source/grep.exe "\\3" ../inputs/grep1.dat  > ../outputs/t87 2>&1
cmp -s ../outputs/t87 ../outputs.alt/t87 || echo different results

echo ">>>>>>>>running test 88"
../source/grep.exe "\\4" ../inputs/grep1.dat  > ../outputs/t88 2>&1
cmp -s ../outputs/t88 ../outputs.alt/t88 || echo different results

echo ">>>>>>>>running test 89"
../source/grep.exe "\\5" ../inputs/grep1.dat  > ../outputs/t89 2>&1
cmp -s ../outputs/t89 ../outputs.alt/t89 || echo different results

echo ">>>>>>>>running test 90"
../source/grep.exe "\\6" ../inputs/grep1.dat  > ../outputs/t90 2>&1
cmp -s ../outputs/t90 ../outputs.alt/t90 || echo different results

echo ">>>>>>>>running test 91"
../source/grep.exe "\\7" ../inputs/grep1.dat  > ../outputs/t91 2>&1
cmp -s ../outputs/t91 ../outputs.alt/t91 || echo different results

echo ">>>>>>>>running test 92"
../source/grep.exe "\\8" ../inputs/grep1.dat  > ../outputs/t92 2>&1
cmp -s ../outputs/t92 ../outputs.alt/t92 || echo different results

echo ">>>>>>>>running test 93"
../source/grep.exe "\\9" ../inputs/grep1.dat  > ../outputs/t93 2>&1
cmp -s ../outputs/t93 ../outputs.alt/t93 || echo different results

echo ">>>>>>>>running test 94"
../source/grep.exe "\\)" ../inputs/grep1.dat  > ../outputs/t94 2>&1
cmp -s ../outputs/t94 ../outputs.alt/t94 || echo different results

echo ">>>>>>>>running test 95"
../source/grep.exe "if\\)" ../inputs/grep1.dat  > ../outputs/t95 2>&1
cmp -s ../outputs/t95 ../outputs.alt/t95 || echo different results

echo ">>>>>>>>running test 96"
../source/grep.exe "\[a-z]\\)" ../inputs/grep1.dat  > ../outputs/t96 2>&1
cmp -s ../outputs/t96 ../outputs.alt/t96 || echo different results

echo ">>>>>>>>running test 97"
../source/grep.exe "\\{" ../inputs/grep1.dat  > ../outputs/t97 2>&1
cmp -s ../outputs/t97 ../outputs.alt/t97 || echo different results

echo ">>>>>>>>running test 98"
../source/grep.exe "a\\{" ../inputs/grep1.dat  > ../outputs/t98 2>&1
cmp -s ../outputs/t98 ../outputs.alt/t98 || echo different results

echo ">>>>>>>>running test 99"
../source/grep.exe "\[1-9]\\{" ../inputs/grep1.dat  > ../outputs/t99 2>&1
cmp -s ../outputs/t99 ../outputs.alt/t99 || echo different results

echo ">>>>>>>>running test 100"
../source/grep.exe "\\{2,1}" ../inputs/grep1.dat  > ../outputs/t100 2>&1
cmp -s ../outputs/t100 ../outputs.alt/t100 || echo different results

echo ">>>>>>>>running test 101"
../source/grep.exe "a\\{2,1}" ../inputs/grep1.dat  > ../outputs/t101 2>&1
cmp -s ../outputs/t101 ../outputs.alt/t101 || echo different results

echo ">>>>>>>>running test 102"
../source/grep.exe "\\{1" ../inputs/grep1.dat  > ../outputs/t102 2>&1
cmp -s ../outputs/t102 ../outputs.alt/t102 || echo different results

echo ">>>>>>>>running test 103"
../source/grep.exe "\\{1,2" ../inputs/grep1.dat  > ../outputs/t103 2>&1
cmp -s ../outputs/t103 ../outputs.alt/t103 || echo different results

echo ">>>>>>>>running test 104"
../source/grep.exe "a\\{1" ../inputs/grep1.dat  > ../outputs/t104 2>&1
cmp -s ../outputs/t104 ../outputs.alt/t104 || echo different results

echo ">>>>>>>>running test 105"
../source/grep.exe "\\{1\\{" ../inputs/grep1.dat  > ../outputs/t105 2>&1
cmp -s ../outputs/t105 ../outputs.alt/t105 || echo different results

echo ">>>>>>>>running test 106"
../source/grep.exe "\\{1,2\\{" ../inputs/grep1.dat  > ../outputs/t106 2>&1
cmp -s ../outputs/t106 ../outputs.alt/t106 || echo different results

echo ">>>>>>>>running test 107"
../source/grep.exe "\[a-z]\\{1,2\\{" ../inputs/grep1.dat  > ../outputs/t107 2>&1
cmp -s ../outputs/t107 ../outputs.alt/t107 || echo different results

echo ">>>>>>>>running test 108"
../source/grep.exe "a\\{1,2\\}" ../inputs/grep1.dat  > ../outputs/t108 2>&1
cmp -s ../outputs/t108 ../outputs.alt/t108 || echo different results

echo ">>>>>>>>running test 109"
../source/grep.exe "\[1-9]\\{1,2\\}" ../inputs/grep1.dat  > ../outputs/t109 2>&1
cmp -s ../outputs/t109 ../outputs.alt/t109 || echo different results

echo ">>>>>>>>running test 110"
../source/grep.exe "A\\{1,2\\}" ../inputs/grep1.dat  > ../outputs/t110 2>&1
cmp -s ../outputs/t110 ../outputs.alt/t110 || echo different results

echo ">>>>>>>>running test 111"
../source/grep.exe "A\\{0\\}" ../inputs/grep1.dat  > ../outputs/t111 2>&1
cmp -s ../outputs/t111 ../outputs.alt/t111 || echo different results

echo ">>>>>>>>running test 112"
../source/grep.exe "1\\{0\\}" ../inputs/grep1.dat  > ../outputs/t112 2>&1
cmp -s ../outputs/t112 ../outputs.alt/t112 || echo different results

echo ">>>>>>>>running test 113"
../source/grep.exe "\[a-z]\\{0\\}" ../inputs/grep1.dat  > ../outputs/t113 2>&1
cmp -s ../outputs/t113 ../outputs.alt/t113 || echo different results

echo ">>>>>>>>running test 114"
../source/grep.exe "\\(" ../inputs/grep1.dat  > ../outputs/t114 2>&1
cmp -s ../outputs/t114 ../outputs.alt/t114 || echo different results

echo ">>>>>>>>running test 115"
../source/grep.exe "a\\(" ../inputs/grep1.dat  > ../outputs/t115 2>&1
cmp -s ../outputs/t115 ../outputs.alt/t115 || echo different results

echo ">>>>>>>>running test 116"
../source/grep.exe "a\\(a" ../inputs/grep1.dat  > ../outputs/t116 2>&1
cmp -s ../outputs/t116 ../outputs.alt/t116 || echo different results

echo ">>>>>>>>running test 117"
../source/grep.exe "\\|\\(a\\|b\\)1*2\\?3\\+" ../inputs/grep1.dat  > ../outputs/t117 2>&1
cmp -s ../outputs/t117 ../outputs.alt/t117 || echo different results

echo ">>>>>>>>running test 118"
../source/grep.exe "\\|\\(if\\|else\\)1*2\\?3\\+" ../inputs/grep1.dat  > ../outputs/t118 2>&1
cmp -s ../outputs/t118 ../outputs.alt/t118 || echo different results

echo ">>>>>>>>running test 119"
../source/grep.exe "\\|\\(for\\|12345\\)a*b\\?c\\+" ../inputs/grep1.dat  > ../outputs/t119 2>&1
cmp -s ../outputs/t119 ../outputs.alt/t119 || echo different results

echo ">>>>>>>>running test 120"
../source/grep.exe "a" ../inputs/biginput.dat  > ../outputs/t120 2>&1
cmp -s ../outputs/t120 ../outputs.alt/t120 || echo different results

echo ">>>>>>>>running test 121"
../source/grep.exe "\[a-z]" ../inputs/biginput.dat  > ../outputs/t121 2>&1
cmp -s ../outputs/t121 ../outputs.alt/t121 || echo different results

echo ">>>>>>>>running test 122"
../source/grep.exe "5\\|7" ../inputs/biginput.dat  > ../outputs/t122 2>&1
cmp -s ../outputs/t122 ../outputs.alt/t122 || echo different results

echo ">>>>>>>>running test 123"
../source/grep.exe -5 if ../inputs/grep1.dat  > ../outputs/t123 2>&1
cmp -s ../outputs/t123 ../outputs.alt/t123 || echo different results

echo ">>>>>>>>running test 124"
../source/grep.exe -7 else ../inputs/grep1.dat  > ../outputs/t124 2>&1
cmp -s ../outputs/t124 ../outputs.alt/t124 || echo different results

echo ">>>>>>>>running test 125"
../source/grep.exe -4 12345 ../inputs/grep1.dat  > ../outputs/t125 2>&1
cmp -s ../outputs/t125 ../outputs.alt/t125 || echo different results

echo ">>>>>>>>running test 126"
../source/grep.exe "\[\[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t126 2>&1
cmp -s ../outputs/t126 ../outputs.alt/t126 || echo different results

echo ">>>>>>>>running test 127"
../source/grep.exe "1\[\[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t127 2>&1
cmp -s ../outputs/t127 ../outputs.alt/t127 || echo different results

echo ">>>>>>>>running test 128"
../source/grep.exe "a*\[\[:alnum:]]" ../inputs/grep1.dat  > ../outputs/t128 2>&1
cmp -s ../outputs/t128 ../outputs.alt/t128 || echo different results

echo ">>>>>>>>running test 129"
../source/grep.exe -f ../inputs/biginput.dat ../inputs/grep1.dat  > ../outputs/t129 2>&1
cmp -s ../outputs/t129 ../outputs.alt/t129 || echo different results

echo ">>>>>>>>running test 130"
../source/grep.exe -f ../inputs/biginput2.dat ../inputs/grep1.dat  > ../outputs/t130 2>&1
cmp -s ../outputs/t130 ../outputs.alt/t130 || echo different results

echo ">>>>>>>>running test 131"
../source/grep.exe -f ../inputs/input_enter1 ../inputs/grep1.dat  > ../outputs/t131 2>&1
cmp -s ../outputs/t131 ../outputs.alt/t131 || echo different results

echo ">>>>>>>>running test 132"
../source/grep.exe -f ../inputs/input_enter2 ../inputs/grep1.dat  > ../outputs/t132 2>&1
cmp -s ../outputs/t132 ../outputs.alt/t132 || echo different results

echo ">>>>>>>>running test 133"
../source/grep.exe -f ../inputs/input_enter3 ../inputs/grep1.dat  > ../outputs/t133 2>&1
cmp -s ../outputs/t133 ../outputs.alt/t133 || echo different results

echo ">>>>>>>>running test 134"
../source/grep.exe "\\\\" ../inputs/grep1.dat  > ../outputs/t134 2>&1
cmp -s ../outputs/t134 ../outputs.alt/t134 || echo different results

echo ">>>>>>>>running test 135"
../source/grep.exe "1\\\\" ../inputs/grep1.dat  > ../outputs/t135 2>&1
cmp -s ../outputs/t135 ../outputs.alt/t135 || echo different results

echo ">>>>>>>>running test 136"
../source/grep.exe "a\\\\" ../inputs/grep1.dat  > ../outputs/t136 2>&1
cmp -s ../outputs/t136 ../outputs.alt/t136 || echo different results

echo ">>>>>>>>running test 137"
../source/grep.exe "\\^" ../inputs/grep1.dat  > ../outputs/t137 2>&1
cmp -s ../outputs/t137 ../outputs.alt/t137 || echo different results

echo ">>>>>>>>running test 138"
../source/grep.exe "1\\^" ../inputs/grep1.dat  > ../outputs/t138 2>&1
cmp -s ../outputs/t138 ../outputs.alt/t138 || echo different results

echo ">>>>>>>>running test 139"
../source/grep.exe "a\\^" ../inputs/grep1.dat  > ../outputs/t139 2>&1
cmp -s ../outputs/t139 ../outputs.alt/t139 || echo different results

echo ">>>>>>>>running test 140"
../source/grep.exe "1\\|^" ../inputs/grep1.dat  > ../outputs/t140 2>&1
cmp -s ../outputs/t140 ../outputs.alt/t140 || echo different results

echo ">>>>>>>>running test 141"
../source/grep.exe "a\\|^" ../inputs/grep1.dat  > ../outputs/t141 2>&1
cmp -s ../outputs/t141 ../outputs.alt/t141 || echo different results

echo ">>>>>>>>running test 142"
../source/grep.exe "\\(1\\)^" ../inputs/grep1.dat  > ../outputs/t142 2>&1
cmp -s ../outputs/t142 ../outputs.alt/t142 || echo different results

echo ">>>>>>>>running test 143"
../source/grep.exe '\\$' ../inputs/grep1.dat  > ../outputs/t143 2>&1
cmp -s ../outputs/t143 ../outputs.alt/t143 || echo different results

echo ">>>>>>>>running test 144"
../source/grep.exe 'if\\$' ../inputs/grep1.dat  > ../outputs/t144 2>&1
cmp -s ../outputs/t144 ../outputs.alt/t144 || echo different results

echo ">>>>>>>>running test 145"
../source/grep.exe 'main\\$' ../inputs/grep1.dat  > ../outputs/t145 2>&1
cmp -s ../outputs/t145 ../outputs.alt/t145 || echo different results

echo ">>>>>>>>running test 146"
../source/grep.exe '$' ../inputs/grep1.dat  > ../outputs/t146 2>&1
cmp -s ../outputs/t146 ../outputs.alt/t146 || echo different results

echo ">>>>>>>>running test 147"
../source/grep.exe 'if$' ../inputs/grep1.dat  > ../outputs/t147 2>&1
cmp -s ../outputs/t147 ../outputs.alt/t147 || echo different results

echo ">>>>>>>>running test 148"
../source/grep.exe 'main$' ../inputs/grep1.dat  > ../outputs/t148 2>&1
cmp -s ../outputs/t148 ../outputs.alt/t148 || echo different results

echo ">>>>>>>>running test 149"
../source/grep.exe '$if' ../inputs/grep1.dat  > ../outputs/t149 2>&1
cmp -s ../outputs/t149 ../outputs.alt/t149 || echo different results

echo ">>>>>>>>running test 150"
../source/grep.exe 'if$if' ../inputs/grep1.dat  > ../outputs/t150 2>&1
cmp -s ../outputs/t150 ../outputs.alt/t150 || echo different results

echo ">>>>>>>>running test 151"
../source/grep.exe 'if$else' ../inputs/grep1.dat  > ../outputs/t151 2>&1
cmp -s ../outputs/t151 ../outputs.alt/t151 || echo different results

echo ">>>>>>>>running test 152"
../source/grep.exe ">" ../inputs/grep1.dat  > ../outputs/t152 2>&1
cmp -s ../outputs/t152 ../outputs.alt/t152 || echo different results

echo ">>>>>>>>running test 153"
../source/grep.exe "1>" ../inputs/grep1.dat  > ../outputs/t153 2>&1
cmp -s ../outputs/t153 ../outputs.alt/t153 || echo different results

echo ">>>>>>>>running test 154"
../source/grep.exe "1>a" ../inputs/grep1.dat  > ../outputs/t154 2>&1
cmp -s ../outputs/t154 ../outputs.alt/t154 || echo different results

echo ">>>>>>>>running test 155"
../source/grep.exe "B" ../inputs/grep1.dat  > ../outputs/t155 2>&1
cmp -s ../outputs/t155 ../outputs.alt/t155 || echo different results

echo ">>>>>>>>running test 156"
../source/grep.exe "ABCDE" ../inputs/grep1.dat  > ../outputs/t156 2>&1
cmp -s ../outputs/t156 ../outputs.alt/t156 || echo different results

echo ">>>>>>>>running test 157"
../source/grep.exe "\[A-B]" ../inputs/grep1.dat  > ../outputs/t157 2>&1
cmp -s ../outputs/t157 ../outputs.alt/t157 || echo different results

echo ">>>>>>>>running test 158"
../source/grep.exe "*" ../inputs/grep1.dat  > ../outputs/t158 2>&1
cmp -s ../outputs/t158 ../outputs.alt/t158 || echo different results

echo ">>>>>>>>running test 159"
../source/grep.exe "*a" ../inputs/grep1.dat  > ../outputs/t159 2>&1
cmp -s ../outputs/t159 ../outputs.alt/t159 || echo different results

echo ">>>>>>>>running test 160"
../source/grep.exe "*\\(abcde\\)" ../inputs/grep1.dat  > ../outputs/t160 2>&1
cmp -s ../outputs/t160 ../outputs.alt/t160 || echo different results

echo ">>>>>>>>running test 161"
../source/grep.exe "\\+" ../inputs/grep1.dat  > ../outputs/t161 2>&1
cmp -s ../outputs/t161 ../outputs.alt/t161 || echo different results

echo ">>>>>>>>running test 162"
../source/grep.exe "1\\+" ../inputs/grep1.dat  > ../outputs/t162 2>&1
cmp -s ../outputs/t162 ../outputs.alt/t162 || echo different results

echo ">>>>>>>>running test 163"
../source/grep.exe "if\\+" ../inputs/grep1.dat  > ../outputs/t163 2>&1
cmp -s ../outputs/t163 ../outputs.alt/t163 || echo different results

echo ">>>>>>>>running test 164"
../source/grep.exe "+" ../inputs/grep1.dat  > ../outputs/t164 2>&1
cmp -s ../outputs/t164 ../outputs.alt/t164 || echo different results

echo ">>>>>>>>running test 165"
../source/grep.exe "+if" ../inputs/grep1.dat  > ../outputs/t165 2>&1
cmp -s ../outputs/t165 ../outputs.alt/t165 || echo different results

echo ">>>>>>>>running test 166"
../source/grep.exe "+else" ../inputs/grep1.dat  > ../outputs/t166 2>&1
cmp -s ../outputs/t166 ../outputs.alt/t166 || echo different results

echo ">>>>>>>>running test 167"
../source/grep.exe "{" ../inputs/grep1.dat  > ../outputs/t167 2>&1
cmp -s ../outputs/t167 ../outputs.alt/t167 || echo different results

echo ">>>>>>>>running test 168"
../source/grep.exe "if{" ../inputs/grep1.dat  > ../outputs/t168 2>&1
cmp -s ../outputs/t168 ../outputs.alt/t168 || echo different results

echo ">>>>>>>>running test 169"
../source/grep.exe "else{" ../inputs/grep1.dat  > ../outputs/t169 2>&1
cmp -s ../outputs/t169 ../outputs.alt/t169 || echo different results

echo ">>>>>>>>running test 170"
../source/grep.exe "1\\{10,11\\}2" ../inputs/grep1.dat  > ../outputs/t170 2>&1
cmp -s ../outputs/t170 ../outputs.alt/t170 || echo different results

echo ">>>>>>>>running test 171"
../source/grep.exe "a\\{10,11\\}b" ../inputs/grep1.dat  > ../outputs/t171 2>&1
cmp -s ../outputs/t171 ../outputs.alt/t171 || echo different results

echo ">>>>>>>>running test 172"
../source/grep.exe "if\\{10,11\\}else" ../inputs/grep1.dat  > ../outputs/t172 2>&1
cmp -s ../outputs/t172 ../outputs.alt/t172 || echo different results

echo ">>>>>>>>running test 173"
../source/grep.exe "\\." ../inputs/grep1.dat  > ../outputs/t173 2>&1
cmp -s ../outputs/t173 ../outputs.alt/t173 || echo different results

echo ">>>>>>>>running test 174"
../source/grep.exe "1\\.a" ../inputs/grep1.dat  > ../outputs/t174 2>&1
cmp -s ../outputs/t174 ../outputs.alt/t174 || echo different results

echo ">>>>>>>>running test 175"
../source/grep.exe "if\\.else" ../inputs/grep1.dat  > ../outputs/t175 2>&1
cmp -s ../outputs/t175 ../outputs.alt/t175 || echo different results

echo ">>>>>>>>running test 176"
../source/grep.exe "\\\[" ../inputs/grep1.dat  > ../outputs/t176 2>&1
cmp -s ../outputs/t176 ../outputs.alt/t176 || echo different results

echo ">>>>>>>>running test 177"
../source/grep.exe "if\\\[" ../inputs/grep1.dat  > ../outputs/t177 2>&1
cmp -s ../outputs/t177 ../outputs.alt/t177 || echo different results

echo ">>>>>>>>running test 178"
../source/grep.exe "if\\\[else" ../inputs/grep1.dat  > ../outputs/t178 2>&1
cmp -s ../outputs/t178 ../outputs.alt/t178 || echo different results

echo ">>>>>>>>running test 179"
../source/grep.exe -i "\[A-z1]" ../inputs/grep1.dat  > ../outputs/t179 2>&1
cmp -s ../outputs/t179 ../outputs.alt/t179 || echo different results

echo ">>>>>>>>running test 180"
../source/grep.exe -i "\[C-x2]" ../inputs/grep1.dat  > ../outputs/t180 2>&1
cmp -s ../outputs/t180 ../outputs.alt/t180 || echo different results

echo ">>>>>>>>running test 181"
../source/grep.exe -i "if\[Xx5]" ../inputs/grep1.dat  > ../outputs/t181 2>&1
cmp -s ../outputs/t181 ../outputs.alt/t181 || echo different results

echo ">>>>>>>>running test 182"
../source/grep.exe -X grep 12345 ../inputs/grep1.dat  > ../outputs/t182 2>&1
cmp -s ../outputs/t182 ../outputs.alt/t182 || echo different results

echo ">>>>>>>>running test 183"
../source/grep.exe -X grep abcde ../inputs/grep1.dat  > ../outputs/t183 2>&1
cmp -s ../outputs/t183 ../outputs.alt/t183 || echo different results

echo ">>>>>>>>running test 184"
../source/grep.exe -X grep if ../inputs/grep1.dat  > ../outputs/t184 2>&1
cmp -s ../outputs/t184 ../outputs.alt/t184 || echo different results

echo ">>>>>>>>running test 185"
../source/grep.exe -e 1 -e 2 ../inputs/grep1.dat  > ../outputs/t185 2>&1
cmp -s ../outputs/t185 ../outputs.alt/t185 || echo different results

echo ">>>>>>>>running test 186"
../source/grep.exe -e a -e b ../inputs/grep1.dat  > ../outputs/t186 2>&1
cmp -s ../outputs/t186 ../outputs.alt/t186 || echo different results

echo ">>>>>>>>running test 187"
../source/grep.exe -e if -e else ../inputs/grep1.dat  > ../outputs/t187 2>&1
cmp -s ../outputs/t187 ../outputs.alt/t187 || echo different results

echo ">>>>>>>>running test 188"
../source/grep.exe -e 12345 -e abcde -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t188 2>&1
cmp -s ../outputs/t188 ../outputs.alt/t188 || echo different results

echo ">>>>>>>>running test 189"
../source/grep.exe -e if -e else -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t189 2>&1
cmp -s ../outputs/t189 ../outputs.alt/t189 || echo different results

echo ">>>>>>>>running test 190"
../source/grep.exe -e 1 -e 2 -e 3 -e 4 -e 5 -e 12345 -f ../inputs/input_1.dat ../inputs/grep1.dat  > ../outputs/t190 2>&1
cmp -s ../outputs/t190 ../outputs.alt/t190 || echo different results

echo ">>>>>>>>running test 191"
../source/grep.exe -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t191 2>&1
cmp -s ../outputs/t191 ../outputs.alt/t191 || echo different results

echo ">>>>>>>>running test 192"
../source/grep.exe -i -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t192 2>&1
cmp -s ../outputs/t192 ../outputs.alt/t192 || echo different results

echo ">>>>>>>>running test 193"
../source/grep.exe -v -f ../inputs/input_2.dat ../inputs/grep1.dat  > ../outputs/t193 2>&1
cmp -s ../outputs/t193 ../outputs.alt/t193 || echo different results

echo ">>>>>>>>running test 194"
../source/grep.exe "\\(\\b\\)*" ../inputs/grep1.dat  > ../outputs/t194 2>&1
cmp -s ../outputs/t194 ../outputs.alt/t194 || echo different results

echo ">>>>>>>>running test 195"
../source/grep.exe "if\\(\\b\\)*" ../inputs/grep1.dat  > ../outputs/t195 2>&1
cmp -s ../outputs/t195 ../outputs.alt/t195 || echo different results

echo ">>>>>>>>running test 196"
../source/grep.exe "\\(\\b\\)\\+" ../inputs/grep1.dat  > ../outputs/t196 2>&1
cmp -s ../outputs/t196 ../outputs.alt/t196 || echo different results

echo ">>>>>>>>running test 197"
../source/grep.exe "\\(\\a|b*\\|c\\?|d\\+\\)\\{1\\}" ../inputs/grep1.dat  > ../outputs/t197 2>&1
cmp -s ../outputs/t197 ../outputs.alt/t197 || echo different results

echo ">>>>>>>>running test 198"
../source/grep.exe "\\(\\if|else*\\|for\\?|while\\+\\)\\{1\\}" ../inputs/grep1.dat  > ../outputs/t198 2>&1
cmp -s ../outputs/t198 ../outputs.alt/t198 || echo different results

echo ">>>>>>>>running test 199"
../source/grep.exe "\\(\\do|12345*\\|main\\?|A\\+\\)\\{1\\}" ../inputs/grep1.dat  > ../outputs/t199 2>&1
cmp -s ../outputs/t199 ../outputs.alt/t199 || echo different results

