/* #define FAULTY_F_DG_1 */
/* #define FAULTY_F_DG_2 */
/* #define FAULTY_F_DG_3 */
/* #define FAULTY_F_DG_4 */
/* #define FAULTY_F_DG_5 */
/* #define FAULTY_F_DG_6 */
/* #define FAULTY_F_DG_7 */
/* #define FAULTY_F_DG_8 */
/* #define FAULTY_F_DG_9 */
/* #define FAULTY_F_DG_10 */
/* #define FAULTY_F_KP_1 */
/* #define FAULTY_F_KP_2 */
/* #define FAULTY_F_KP_3 */
/* #define FAULTY_F_KP_5 */
/* #define FAULTY_F_KP_6 */
/* #define FAULTY_F_KP_7 */
/* #define FAULTY_F_KP_8 */
/* #define FAULTY_F_KP_9 */
