#!/usr/bin/python
#
# The Pythia oracle should not contain any test cases with a non-zero return
# code
#
import sys
import json

def main():
    tests = []
    with open("tests.txt", "r") as f:
        for test in f:
            tests.append(test.strip())

    with open("oracle.pythia.json", "r") as f:
        cases = json.load(f)
        for (i, case) in enumerate(cases):
            if case['retcode'] != 0:
                name = tests[i]
                print("Oracle sanity checking failed: {} [#{}]".format(name, i))
                sys.exit(1)

    sys.exit(0)

if __name__ == "__main__":
    main()
