#!/usr/bin/python
import os
import json

def generate():
    # find the number of positive and negative tests
    negative = positive = None
    with open("map.pythia.json", "r") as f_map:
        test_ids = json.load(f_map).keys()
        negative = sum(1 for t in test_ids if t[0] == 'n')
        positive = sum(1 for t in test_ids if t[0] == 'p')
        if negative == 0:
            print("WARNING: no negative tests")
        if positive == 0:
            print("WARNING: no positive tests")
   
    # read and complete the problem template
    bfr = ""
    with open("problem.template.json", "r") as f_tpl:
        bfr = f_tpl.read()
        bfr = bfr.replace("<<NEGATIVE_TESTS>>", str(negative))
        bfr = bfr.replace("<<POSITIVE_TESTS>>", str(positive))
        bfr = bfr.replace("<<PROGRAM_NAME>>", os.environ['PROGRAM_NAME'])
        bfr = bfr.replace("<<SCENARIO_NAME>>", os.environ['SCENARIO_NAME'])

    # save the complete problem file to disk
    with open("problem.json", "w") as f_problem:
        f_problem.write(bfr)

    # destroy the template file
    os.remove("problem.template.json")

    print("Generated problem.json")

if __name__ == "__main__":
    generate()
