#!/bin/bash
#
# grep -n "^p1$" test.mapping | cut -f1 -d :

# How many test cases do we have?
num_tests=$(wc -l test.commands)

# Keep a counter of the number of positive and negative tests that we've
# encountered so far
negatives=0
positives=0

# Ensure the mapping file exists and is empty
rm -f test.mapping && touch test.mapping

# Execute each test case
for (( i = 1; i < num_tests; i++ )); do
  if test-runner $i; then
    positives=$((positives+1))
    test_name="^p${positives}$"
  else
    negatives=$((negatives+1))
    test_name="^n${negatives}$"
  fi
  echo "$test_name" >> test.mapping
done

# Save number of negatives and positives
