#!/bin/bash
#
# Generates a mapping from the test suite commands in this directory to their
# identifier, saving the result to "test.mapping" within the same directory.
# Each line in "test.mapping" gives the corresponding test identifier for the
# test on the same line in "test.commands".
#
# Must be provided the path to the executable file that should be used to
# generate the test outputs.
#
# Usage:
# generate-mapping <executable>
EXECUTABLE=$1

# How many test cases do we have?
num_tests=$(wc -l test.commands)

# Keep a counter of the number of positive and negative tests that we've
# encountered so far
negatives=0
positives=0

# Ensure the mapping file exists and is empty
rm -f test.mapping && touch test.mapping

# Execute each test case
for (( i = 1; i < num_tests; i++ )); do
  if run-test-with-num $i $EXECUTABLE; then
    positives=$((positives+1))
    test_name="^p${positives}$"
  else
    negatives=$((negatives+1))
    test_name="^n${negatives}$"
  fi
  echo "$test_name" >> test.mapping
done

# Save number of negatives and positives
