#!/bin/bash
#
# Using the list of test commands provided in the current directory, together
# with their associated inputs and expected outputs (located in inputs/ and
# oracle/, respectively), this script runs a test with a given number on a
# program with a provided executable and returns 0 if the produced output
# matches the expected output.
#
# Usage:
# run-test-with-num <num> <executable>
NUM=$0
EXECUTABLE=$1
TEST_FILE="test.commands"
ORACLE="oracle"
INPUTS="inputs"

# Generate the test command
COMMAND=$(sed "${NUM}q;d; s#\$EXECUTABLE#${EXECUTABLE}#1; s#\$INPUTS#${INPUTS}#1" ${TEST_FILE})

# Compare the output of the test against the expected output
$COMMAND |& diff $ORACLE/t${NUM} -- &> /dev/null && exit 0
