#!/bin/bash

# Find number of tests
num_tests=$(wc -l < test.commands)

# Execute each test case
for (( i = 1; i<${num_tests}; i++ )); do
  if run-test-with-num $i; then
    echo "PASSED: $i"
  else
    echo "FAILED: $i"
  fi
done
